### PR TITLE
FreeBSD compatibility fix

### PR DESCRIPTION
**Pull request by karolyi**
Hey guys,

I managed to compile the whole project on FreeBSD, with this little adjustment in the `CMakeLists.txt` file.

Cheers

### CODE REVIEW

**Comment by chrisn** [comment]
Hi László,

The CMakeLists.txt file should really be cross-platform, so I'd like to avoid having any platform-specific paths in it. There is no `/usr/local` directory on Windows, for example. (We don't have a working Windows build yet, but that's still a goal...)

Reading [this page](https://cmake.org/Wiki/CMake:How_To_Find_Libraries), I think that the right approach is to add the include path determined by each `find_package` call, for example:

    find_package (LibGD REQUIRED)
    if (LIBGD_FOUND)
        include_directories(${LIBGD_INCLUDE_DIR})
    endif (LIBGD_FOUND)

and the same for each of the other dependencies.

I'd be happy to merge a PR along these lines, if it's tested to work OK.

Thanks for your contribution!

Chris

**Comment by karolyi** [comment]
I'm sorry but I don't have enough knowledge on that file type to fulfill your needs... I just googled around and figured out that adding that one line helps in successful compilation, and according to the issues here, I saw that many others had this problem. Hence the small pull request.

I think `/usr/local` is a pretty common include path amongst posix systems, so I think it shouldn't be an issue if you merge it as it is, but feel free to close the pull request without merging if you like.

**Comment by chrisn** [comment]
I've just pushed a change to the [include-paths](https://github.com/bbcrd/audiowaveform/tree/include-paths) branch. Would you mind testing this and let us know if it works for you? Thanks!

**Comment by karolyi** [comment]
Hey @chrisn,

reporting that it's compiling on FreeBSD.

Cheers,
László

**Comment by chrisn** [comment]
I've merged the include-paths branch to master, so closing this. Thank you for your help!

**Pull request closed without merging**
